# Generated by Django 5.2.5 on 2025-08-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Справочник',
                'db_table': 'guide',
            },
        ),
        migrations.CreateModel(
            name='GuideItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resincore.guide', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'db_table': 'guide_item',
            },
        ),
    ]
